# Generated by Django 4.1.4 on 2022-12-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=0, upload_to='posters'),
            preserve_default=False,
        ),
    ]
